# Generated by Django 6.0.3 on 2026-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conférence'), ('concert', 'Concert'), ('atelier', 'Atelier'), ('sport', 'Sport'), ('networking', 'Networking'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
